<?php

/**
 * @file
 * Install, update and uninstall functions for the Product of the Day module.
 */

/**
 * Implements hook_install().
 */
function product_of_the_day_install() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function product_of_the_day_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_schema().
 */
function product_of_the_day_schema() {
  $schema['product_of_the_day'] = [
    'fields' => [
      'id'          => ['type'=>'serial','not null'=>TRUE],
      'name'        => ['type'=>'varchar','length'=>255,'not null'=>TRUE],
      'summary'     => ['type'=>'text','not null'=>FALSE],
      'image_fid'   => ['type'=>'int','not null'=>TRUE],
      'is_featured' => ['type'=>'int','size'=>'tiny','default'=>0],
      'created'     => ['type'=>'int','not null'=>TRUE],
      'changed'     => ['type'=>'int','not null'=>TRUE],
    ],
    'primary key' => ['id'],
  ];
  $schema['product_clicks'] = [
    'fields' => [
      'id'         => ['type'=>'serial','not null'=>TRUE],
      'product_id' => ['type'=>'int','not null'=>TRUE],
      'timestamp'  => ['type'=>'int','not null'=>TRUE],
    ],
    'primary key' => ['id'],
  ];
  return $schema;
}

/**
 * Implements hook_requirements().
 */
function product_of_the_day_requirements($phase) {
  $requirements = [];

  if ($phase == 'runtime') {
    $value = mt_rand(0, 100);
    $requirements['product_of_the_day_status'] = [
      'title' => t('Product of the Day status'),
      'value' => t('Product of the Day value: @value', ['@value' => $value]),
      'severity' => $value > 50 ? REQUIREMENT_INFO : REQUIREMENT_WARNING,
    ];
  }

  return $requirements;
}
